---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.guest_meeting_registration.name"

ignore_missing:
  - decidim.meetings.meetings.show.join
  - decidim.meetings.meetings.show.no_slots_available
  - decidim.meetings.meetings.show.remaining_slots
  - decidim.admin.organization.update.success
  - decidim.admin.organization.update.error
