name: "[CI] Test"

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 16.9.1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        folder:
          - "spec/accountability"
          - "spec/budgets"
          - "spec/commands"
          - "spec/elections"
          - "spec/events"
          - "spec/forms"
          - "spec/models"
          - "spec/proposals/cells"
          - "spec/proposals/commands"
          - "spec/proposals/controllers"
          - "spec/proposals/events"
          - "spec/proposals/forms"
          - "spec/proposals/helpers"
          - "spec/proposals/lib"
          - "spec/proposals/models"
          - "spec/proposals/permissions"
          - "spec/proposals/presenters"
          - "spec/proposals/queries"
          - "spec/proposals/services"
          - "spec/proposals/system/admin"
          - "spec/proposals/system/amendable"
          - "spec/proposals/system/*.rb"
          - "spec/proposals/types"
          - "spec/sortitions"
          - "spec/system"
    uses: ./.github/workflows/test_app.yml
    secrets: inherit
    name: Testing ${{ matrix.folder }}
    with:
      folder: ${{ matrix.folder }}
